services:
  # PostgreSQL Database
  - type: pserv
    name: hazop-db
    env: docker
    region: oregon
    plan: free
    ipAllowList: []
    databases:
      - name: hazop_db
        user: hazop_user

  # Backend API Service
  - type: web
    name: hazop-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "from app.database import Base, engine; Base.metadata.create_all(bind=engine)"
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hazop-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: hazop-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: |
      cd frontend
      npm install
      VITE_API_URL=$BACKEND_URL npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: hazop-backend
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
