databases:
  - name: hazop-db
    databaseName: hazop_db
    user: hazop_user
    plan: free

services:
  # Backend API Service
  - type: web
    name: hazop-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hazop-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: hazop-frontend
          envVarKey: RENDER_EXTERNAL_URL
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: hazop-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: hazop-backend
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
